#---------------------------General Params-------------------------------------#


case : "VRM"

data_folder : 'data_VRM'
plots_folder : 'plots_VRM'


#--------------------------Time Params--------------------------------------#
nTimeSteps : 251    #number of lagrangian time-steps
writeInterval_plots : 25     

deltaTc : 0.1      #lagrangian, convection time-step
N_initial : 6       #no. of timesteps skipped from t = 0 (accounting for diffusion of a dirac delta)

#---------------------------Lagrangian Params-------------------------------------#

vInfx : 0.0           #freestream velocity in x direction
vInfy : 0.0           #freestream velocity in y direction
overlap : 2.0         #blobs' overlap ratio

nu : 1.0
gammaC : 1.0

  #Computation Params
hardware : "gpu"
method : "direct"

#Blob Control Params
method_popControl : 'implicit'
stepRedistribution : 0
stepPopulationControl : 0
gThresholdLocal : 1.0e-12
gThresholdGlobal : 1.0e-12
blobsRedistribute : 'all'

  #Blob Diffusion Params
method_diffusion : 'fixed_vrm'

avrm_params : {'useRelativeThresholds' : True, 'ignoreThreshold' : 1.0e-6,
 'adaptThreshold' : 1.0e-3 ,'Clapse' : 0.1, 'merge_flag' : True, 'stepMerge' : 1,
  'mergeThreshold' : 0.001}

  #Time integration Params
time_integration_method : 'rk4'

  #Kernel params
kernel : 'gauss'
coreSize : 'fixed'

  #xShift,yShift
xShift : 0.0
yShift : 0.0

#--------------------------- Compression Params -------------------------------------#

compressionFlag : False
compression_stride : 10000

compression_method : 'remesh'
compression_params : {'Csigma' : 1.0, 'margin' : 0.05, 'sigma_max' : 0.1, 'compression' : 0.75, 'assignment_type' : 'M4prime'}

support_method : 'all'
support_params : {}

#---------------------------Plot Params-------------------------------------#
nPlotPoints : 100    #plot points in each direction
xMinPlot : -2.0       #minimum x to plot
xMaxPlot : 2.0       #maximum x to plot
yMinPlot : -2.0       #minimum y to plot
yMaxPlot : 2.0        #maximum y to plot


run_analytical_flag : True
plot_flag : True